### ISSUE TITLE
Mono integration (generally Mac OS X)

### ISSUE THREAD

**Issue by jkaflik** [snakedeveloper/GMK-Assembler#1]
While Game Maker has Mac OS X version, GMK-Assembler should work on that OS too (with Mono, so any POSIX system is included).
1. Does OS X .gmk have any differences in structure?
   ...

Let's discuss on it!

**Comment by snakedeveloper** [comment]
I'm not sure if the Mac version of .gmk files has any differences between the ones created on Windows. But currently Game Maker for Mac is not up-to-date with Windows GM, and thus its file format is most probably left unchanged since it's still GM7. GMK Assembler does not support GM7 and lower versions of GameMaker, and won't support them in the future releases.

**Comment by jkaflik** [comment]
So we need to wait for futher GM4Mac updates, but who cares, we don't need that to port
